package org.labkey.query;

import org.labkey.api.data.ColumnInfo;
import org.labkey.api.data.TableInfo;
import org.labkey.api.query.FieldKey;

import java.util.ArrayList;
import java.util.List;

/**
 * User: jeckels
 * Date: 11/21/12
 */
public class AutoGeneratedInsertCustomView extends AutoGeneratedCustomView
{
    public static final String NAME = "~~INSERT~~";

    public AutoGeneratedInsertCustomView(QueryDefinitionImpl queryDef)
    {
        super(queryDef, NAME);
    }

    @Override
    protected List<FieldKey> getFieldKeysToShow(TableInfo table)
    {
        List<FieldKey> result = new ArrayList<FieldKey>();
        for (ColumnInfo col : table.getUserEditableColumns())
        {
            if (col.isShownInInsertView())
            {
                result.add(col.getFieldKey());
            }
        }
        return result;
    }
}
