UPDATE study.Cohort
    SET LSID='UPGRADE_REQUIRED'
    WHERE LSID IS NULL;

ALTER TABLE study.Cohort
  ALTER COLUMN LSID SET NOT NULL;

ALTER TABLE study.Visit
    ADD COLUMN LSID VARCHAR(200);

UPDATE study.Visit
    SET LSID='UPGRADE_REQUIRED'
    WHERE LSID IS NULL;

ALTER TABLE study.Visit
  ALTER COLUMN LSID SET NOT NULL;

ALTER TABLE study.Study
    ADD COLUMN LSID VARCHAR(200);

UPDATE study.Study
    SET LSID='UPGRADE_REQUIRED'
    WHERE LSID IS NULL;

ALTER TABLE study.Study
  ALTER COLUMN LSID SET NOT NULL;