ALTER TABLE study.StudyData ADD COLUMN Created TIMESTAMP NULL, ADD COLUMN Modified TIMESTAMP NULL, ADD COLUMN VisitDate TIMESTAMP NULL;
ALTER TABLE study.DataSet ADD COLUMN EntityId ENTITYID;
ALTER TABLE study.Study ADD COLUMN EntityId ENTITYID;

CREATE TABLE study.AssayRun
    (
	RowId SERIAL,
    AssayType VARCHAR(200) NOT NULL,
    Container ENTITYID NOT NULL,
    CONSTRAINT PK_AssayRun PRIMARY KEY (RowId)
    );
