import org.labkey.gradle.util.BuildUtils
import org.labkey.gradle.util.ExternalDependency

plugins {
    id 'org.labkey.build.module'
}

sourceSets {
    main {
        resources {
            srcDirs = ['src'] // src is included because it contains some image and text files
            exclude '**/*.java'
            exclude '**/*.jsp'
        }
    }
}

BuildUtils.addExternalDependency(
        project,
        new ExternalDependency(
                "ca.uhn.hapi.fhir:hapi-fhir-base:8.6.1",
                "FHIR base",
                "Eclipse",
                "https://eclipse-ee4j.github.io/jaxb-ri/",
                "Eclipse Distribution License v1.0",
                "http://www.eclipse.org/org/documents/edl-v10.php",
                "Parsing XML"
        )
)

BuildUtils.addExternalDependency(
        project,
        new ExternalDependency(
                "ca.uhn.hapi.fhir:hapi-fhir-structures-r4:8.6.1",
                "FHIR base",
                "Eclipse",
                "https://eclipse-ee4j.github.io/jaxb-ri/",
                "Eclipse Distribution License v1.0",
                "http://www.eclipse.org/org/documents/edl-v10.php",
                "Parsing XML"
        )
)

dependencies {
    implementation "org.eclipse.angus:angus-mail:${angusMailVersion}"
    BuildUtils.addLabKeyDependency(project: project, config: "implementation", depProjectPath: BuildUtils.getPlatformModuleProjectPath(project.gradle, "assay"), depProjectConfig: "apiJarFile")
    BuildUtils.addLabKeyDependency(project: project, config: "jspImplementation", depProjectPath: BuildUtils.getPlatformModuleProjectPath(project.gradle, "assay"), depProjectConfig: "apiJarFile")

    BuildUtils.addLabKeyDependency(project: project, config: "modules", depProjectPath: BuildUtils.getPlatformModuleProjectPath(project.gradle, "experiment"), depProjectConfig: "published", depExtension: "module")
    BuildUtils.addLabKeyDependency(project: project, config: "modules", depProjectPath: BuildUtils.getPlatformModuleProjectPath(project.gradle, "pipeline"), depProjectConfig: "published", depExtension: "module")
    BuildUtils.addLabKeyDependency(project: project, config: "modules", depProjectPath: BuildUtils.getPlatformModuleProjectPath(project.gradle, "query"), depProjectConfig: "published", depExtension: "module")
    BuildUtils.addLabKeyDependency(project: project, config: "modules", depProjectPath: BuildUtils.getPlatformModuleProjectPath(project.gradle, "assay"), depProjectConfig: "published", depExtension: "module")
}
