/*
 * Copyright (c) 2018-2026 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.labkey.gradle.util.BuildUtils
import org.labkey.gradle.util.ExternalDependency

plugins {
   id 'org.labkey.build.module'
}

sourceSets {
   main {
      resources {
         srcDirs = ['src'] // src is included because it contains some sql scripts
         exclude '**/*.java'
         exclude '**/*.jsp'
      }
   }
}


dependencies{
   BuildUtils.addExternalDependency(
           project,
           new ExternalDependency(
                   "net.sf.opencsv:opencsv:${opencsvVersion}",
                   'Open CSV',
                   'Open CSV',
                   'http://opencsv.sf.net',
                   ExternalDependency.APACHE_2_LICENSE_NAME,
                   ExternalDependency.APACHE_2_LICENSE_URL,
                   'A simple library for reading and writing CSV in Java'
           )
   )
   BuildUtils.addExternalDependency(
           project,
           new ExternalDependency(
                   "org.apache.commons:commons-math3:${commonsMath3Version}",
                   "Commons Math",
                   "Apache",
                   "http://commons.apache.org/math/",
                   ExternalDependency.APACHE_2_LICENSE_NAME,
                   ExternalDependency.APACHE_2_LICENSE_URL,
                   "Lightweight, self-contained mathematics and statistics components"
           )
   )
   BuildUtils.addLabKeyDependency(project: project, config: "modules", depProjectPath: BuildUtils.getPlatformModuleProjectPath(project.gradle, "pipeline"), depProjectConfig: "published", depExtension: "module")
   BuildUtils.addLabKeyDependency(project: project, config: "modules", depProjectPath: BuildUtils.getPlatformModuleProjectPath(project.gradle, "query"), depProjectConfig: "published", depExtension: "module")
}
