/*
 * Copyright (c) 2018 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.labkey.core.view.template.bootstrap;

import org.jetbrains.annotations.Nullable;
import org.labkey.api.admin.CoreUrls;
import org.labkey.api.module.ModuleLoader;
import org.labkey.api.security.permissions.TroubleshooterPermission;
import org.labkey.api.settings.AdminConsole;
import org.labkey.api.settings.AppProps;
import org.labkey.api.settings.ExperimentalFeatureService;
import org.labkey.api.util.HtmlString;
import org.labkey.api.util.HtmlStringBuilder;
import org.labkey.api.util.PageFlowUtil;
import org.labkey.api.view.HttpView;
import org.labkey.api.view.ViewContext;
import org.labkey.api.view.template.WarningProvider;
import org.labkey.api.view.template.WarningService;
import org.labkey.api.view.template.Warnings;
import org.labkey.core.CoreModule;

import java.util.Collection;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.function.Consumer;

import static org.labkey.api.util.PageFlowUtil.urlProvider;

public class WarningServiceImpl implements WarningService
{
    private static volatile Collection<HtmlString> STATIC_ADMIN_WARNINGS = null;
    private static volatile boolean SHOW_ALL_WARNINGS = false;

    // Because of dependencies between WarningService and ExperimentalService, we can't invoke these in a WarningServiceImpl static initializer
    private static class LazyInitializer
    {
        private static final String EXPERIMENTAL_SHOW_ALL_WARNINGS = "experimentalShowAllWarnings";

        static
        {
            if (AppProps.getInstance().isDevMode())
            {
                AdminConsole.addExperimentalFeatureFlag(EXPERIMENTAL_SHOW_ALL_WARNINGS, "Show all admin warnings",
                    "Enable to test the admin warning messages generated by most of the warning providers.", false);
                SHOW_ALL_WARNINGS = ExperimentalFeatureService.get().isFeatureEnabled(EXPERIMENTAL_SHOW_ALL_WARNINGS);
                ExperimentalFeatureService.get().addFeatureListener(EXPERIMENTAL_SHOW_ALL_WARNINGS, (feature, enabled) -> {
                    SHOW_ALL_WARNINGS = enabled;
                    STATIC_ADMIN_WARNINGS = null; // Force static warnings to be re-collected since flag has changed
                });
            }
        }

        private static void init()
        {
        }
    }

    private final Collection<WarningProvider> _providers = new CopyOnWriteArrayList<>();

    @Override
    public boolean showAllWarnings()
    {
        return SHOW_ALL_WARNINGS;
    }

    @Override
    public void register(WarningProvider provider)
    {
        _providers.add(provider);
    }

    @Override
    public void forEachProvider(Consumer<WarningProvider> consumer)
    {
        _providers.forEach(consumer);
    }

    // Check warning conditions that don't change after the server has started up. We'll collect and stash these during
    // the first request after startup is complete. They are also re-collected if the "show all warnings" experimental
    // feature flag is used.
    private static Collection<HtmlString> getStaticAdminWarnings()
    {
        if (STATIC_ADMIN_WARNINGS != null)
        {
            return STATIC_ADMIN_WARNINGS;
        }

        LazyInitializer.init(); // Invoke no-op method to ensure static initializer is executed
        Warnings warnings = Warnings.of(new LinkedList<>());
        WarningService.get().forEachProvider(p -> p.addStaticWarnings(warnings, WarningService.get().showAllWarnings()));
        List<HtmlString> messages = Collections.unmodifiableList(warnings.getMessages());

        if (ModuleLoader.getInstance().isStartupComplete())
        {
            // We should have our full list of warnings at this point, so safe to stash them
            STATIC_ADMIN_WARNINGS = messages;
        }

        return messages;
    }

    private static final String DISMISSAL_SCRIPT_FORMAT =
        """
            (function($) {
                function dismissMessage() {
                    var config = {
                        url: %1$s,
                        method: 'POST',
                        success: function () {$('.lk-dismissable-warn').hide();$('#headerWarningIcon').show();},
                        failure: LABKEY.Utils.displayAjaxErrorResponse
                    };
                    LABKEY.Ajax.request(config);\s
                    return false;
                }
                $('body').on('click', 'a.lk-dismissable-warn-close', function() {
                    dismissMessage();
                });
            })(jQuery);
        """;

    @Override
    public Warnings getWarnings(@Nullable ViewContext context)
    {
        if (context != null)
        {
            if (null == context.getUser())
                throw new IllegalStateException("ViewContext.getUser() was null");
            if (null == context.getRequest())
                throw new IllegalStateException("ViewContext.getUser() was null");
        }

        // Collect warnings
        List<HtmlString> warningMessages = new LinkedList<>();

        if (context == null || context.getUser().hasRootPermission(TroubleshooterPermission.class))
            warningMessages.addAll(getStaticAdminWarnings());

        Warnings warnings = Warnings.of(warningMessages);
        WarningService.get().forEachProvider(p->p.addDynamicWarnings(warnings, context, showAllWarnings()));

        return warnings;
    }

    @Override
    public HtmlString getWarningsHtml(Warnings warnings, ViewContext context)
    {
        HtmlStringBuilder html = HtmlStringBuilder.of(HtmlString.unsafe("<div class=\"alert alert-warning alert-dismissable\">\n<a href=\"#\" class=\"close lk-dismissable-warn-close\" data-dismiss=\"alert\" aria-label=\"dismiss\" title=\"dismiss\">×</a>\n<div class=\"lk-dismissable-warn\">"));
        appendMessageContent(warnings, html);
        html.unsafeAppend("</div>\n");
        CoreUrls coreUrls = urlProvider(CoreUrls.class);
        if (coreUrls != null)
        {
            String dismissURL = coreUrls.getDismissWarningsActionURL(context).toString();
            html.unsafeAppend("<script type=\"text/javascript\" nonce=\"" + HttpView.currentPageConfig().getScriptNonce() + "\">\n");
            html.unsafeAppend(String.format(DISMISSAL_SCRIPT_FORMAT, PageFlowUtil.jsString(dismissURL)));
            html.unsafeAppend("</script>\n");
        }
        html.unsafeAppend("</div>");

        return html.getHtmlString();
    }

    private void appendMessageContent(Warnings warnings, HtmlStringBuilder html)
    {
        if (!warnings.isEmpty())
        {
            List<HtmlString> messages = warnings.getMessages();

            if (messages.size() == 1)
                html.append(messages.get(0));
            else
            {
                html.startTag("ul");
                for (HtmlString msg : messages)
                    html.startTag("li").append(msg).endTag("li");
                html.endTag("ul");
            }
        }
    }

    @Override
    public void rerunSchemaCheck()
    {
        ((CoreModule)ModuleLoader.getInstance().getCoreModule()).rerunSchemaCheck();
    }
}
