<%@ page import="org.labkey.api.wiki.WikiRendererType" %>
<%@ page import="org.labkey.api.util.PageFlowUtil" %>
<%@ page import="org.labkey.wiki.WikiController" %>
<%@ page import="org.labkey.api.view.JspView" %>
<%@ page import="org.labkey.api.view.HttpView" %>
<%
    JspView<WikiController.NewPageForm> me = (JspView<WikiController.NewPageForm>) HttpView.currentView();
    WikiController.NewPageForm model = me.getModelBean();
%>

<form action="editWiki.view" method="GET" id="wiki-format-form">
    <% if(null != model.getRedirect()) { %>
    <input type="hidden" name="redirect" value="<%=PageFlowUtil.filter(model.getRedirect())%>"/>
    <% } %>
    <% if(null != model.getName()) { %>
    <input type="hidden" name="defName" value="<%=PageFlowUtil.filter(model.getName())%>"/>
    <% } %>
    <% if(null != model.getPageId()) { %>
    <input type="hidden" name="pageId" value="<%=PageFlowUtil.filter(model.getPageId())%>"/>
    <% } %>
    <% if(model.getIndex() > 0) { %>
    <input type="hidden" name="index" value="<%=model.getIndex()%>"/>
    <% } %>

    <p>Which format would you like to use for your new page?</p>

    <input type="radio" name="format" value="<%=WikiRendererType.HTML.name()%>" id="rbHtml" checked="1"><label for="rbHtml">HTML Format</label>
    <blockquote>
        Pages in Hypertext Markup Language (HTML) Format can be authored either in a visual or source
        editor. The visual editor is similar to a word processor, providing helpful buttons to insert
        bulleted or numbered lists, tables, hyperlinks, headings, bold or italic text, etc. The source
        editor allows you to further customize the HTML generated by the visual editor.
    </blockquote>
    <input type="radio" name="format" value="<%=WikiRendererType.RADEOX.name()%>" id="rbRadeox"><label for="rbRadeox">Wiki Format</label>
    <blockquote>
        Pages in Wiki Format are authored in plain text using simple markup characters to indicate bold,
        italics, headings, hyperlinks, bulleted or numbered lists, tables, etc. The specific Wiki markup language
        is a variant of the <a href="http://snipsnap.org/space/snipsnap-help">SnipSnap language</a>.
    </blockquote>
    <input type="radio" name="format" value="<%=WikiRendererType.TEXT_WITH_LINKS.name()%>" id="rbText"><label for="rbText">Plain Text Format</label>
    <blockquote>
        Pages in Plain Text format contain no markup at all, so these pages cannot have bold, italics,
        lists, tables, etc. However, all spaces and indentation will be preserved and web addresses (e.g., http://labkey.org)
        will be converted to a hyperlink automatically when the page is displayed to a reader.
    </blockquote>

    <p><%=PageFlowUtil.buttonLink("Create Page", "javascript:{}", "document.getElementById('wiki-format-form').submit();")%></p>
</form>
