<%
/*
 * Copyright (c) 2008-2012 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
%><%@ page import="org.labkey.api.data.ContainerFilter" %><%@ page import="org.labkey.api.view.HttpView" %><%@ page import="org.labkey.api.view.JspView" %><%@ page import="org.labkey.bigiron.sas.SasExportScriptModel" %>
<%
    JspView<SasExportScriptModel> me = (JspView<SasExportScriptModel>) HttpView.currentView();
    SasExportScriptModel model = me.getModelBean();
    me.getViewContext().getResponse().setContentType("text/plain");
    ContainerFilter containerFilter = null;
    if (model.getContainerFilter() != null)
        containerFilter = model.getContainerFilter();
%>/*
 * SAS Script generated by <%=model.getInstallationName()%> on <%=model.getCreatedOn()%>
 *
 * This script makes use of the SAS/LabKey macros and jar files that must be configured on your
 * SAS installation.  See https://www.labkey.org/wiki/home/Documentation/page.view?name=sasAPI
 * for configuration information.
 */

/*  Select rows into a data set called 'mydata' */

%labkeySelectRows(dsn=mydata,
            baseUrl="<%=model.getBaseUrl()%>",
            folderPath="<%=model.getFolderPath()%>",
            schemaName="<%=model.getSchemaName()%>",
            queryName="<%=model.getQueryName()%>"<% if (null != model.getViewName()) {%>,
            viewName="<%=model.getViewName()%>"<% } if (null != model.getSort()) {%>,
            sort=<%=model.getSort()%><% } if (null != model.getFilters()) {%>,
            filter=<%=model.getFilters()%><% } if (null != containerFilter && null != containerFilter.getType()) {%>,
            containerFilter="<%= containerFilter.getType().name() %>"<% } %>);
