/*
 * Copyright (c) 2008-2017 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.labkey.api.reports.report.r;

import org.jetbrains.annotations.Nullable;
import org.labkey.api.reports.report.ScriptOutput;
import org.labkey.api.thumbnail.Thumbnail;
import org.labkey.api.view.HttpView;
import org.labkey.api.view.ViewContext;
import org.labkey.api.reports.Report;

import java.io.File;
import java.io.IOException;
import java.util.Collection;
import java.util.List;
import java.util.Map;

/**
 * Handles substitution parameters for R reports by mapping symbolic names to
 * files on generation, as well as rendering the results.
 *
 * User: Karl Lum
 * Date: May 5, 2008
 */
public interface ParamReplacement
{
    /** unique identifier for this replacement type */
    String getId();

    /** the name portion of the output replacement, must be unique within the R script */
    String getName();
    void setName(String name);

    /**
     * returns a regular expression used to match files generated by the R script, the regex is evaluated
     * against any filename that is not claimed by other param replacements. A regex is escaped in the substitution
     * using the syntax : ${id:regex(expression)}
     */
    @Nullable
    String getRegex();
    void setRegex(String regex);

    /** optional replacement parameter properties */
    Map<String, String> getProperties();
    void setProperties(Map<String, String> properties);

    /** optional annotation to see if a remote executable (Rserve) is creating the parameter */
    boolean isRemote();
    void setRemote(boolean isRemote);

    /**
     * Convert the substitution to its eventual generated file.
     * @param directory - the parent directory to create the generated file (if any, can be null)
     */
    @Nullable
    File convertSubstitution(File directory) throws Exception;

    /**
     * Get and set files associated with the replacement
     * @param file
     */
    void addFile(File file);
    List<File> getFiles();
    void clearFiles();

    String toString();

    void setReport(Report report);
    Report getReport();

    void setHeaderVisible(boolean visible);
    boolean getHeaderVisible();

    HttpView render(ViewContext context);
    @Nullable Thumbnail renderThumbnail(ViewContext context) throws IOException;
    ScriptOutput renderAsScriptOutput(File file) throws Exception;
}
