/*
 * Copyright (c) 2018 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0: http://www.apache.org/licenses/LICENSE-2.0
 */
const fs = require('fs-extra');
const { execSync } = require('child_process');

/**
 * Experimental build configuration to use @labkey/api distribution in lieu of default client/api/core files.
 * For more information see https://github.com/LabKey/labkey-api-js#running-against-a-labkey-server
 */
const USE_LABKEY_API = false;

function copyAPIFiles() {
    log('Copying files from npm package ... ');
    const apiDistDir = __dirname + '/node_modules/@labkey/api/dist/';
    const targetDir = __dirname + '/resources/web/clientapi/';

    const files = [
        'labkey-api-js-core.min.js',
        'labkey-api-js-core.min.js.map'
    ];

    files.forEach((file) => {
        fs.copy(apiDistDir + file, targetDir + file);
    });
    log('Done.\n');
}

function installDependencies() {
    log('Installing dependencies ... ');

    const pkgName = '@labkey/api';
    let output;

    try {
        output = execSync(`npm ls ${pkgName} --json`);
    } catch (ex) {
        output = ex.stdout;
    }

    const result = JSON.parse(output);

    if (result.dependencies === undefined ||
        result.dependencies[pkgName] === undefined) {
        execSync(`npm install ${pkgName} --save-dev --loglevel=error`);
        log('Installed.\n');
    }
    else {
        log('Already Installed.\n');
    }
}

function log(msg) {
    process.stdout.write(msg);
}

function overwriteLibXML() {
    log('Overwriting client API XML lib ... ');
    const clientLibDir = __dirname + '/../api/webapp/';
    const clientLibFileName = 'clientapi_core.lib.xml';

    const libContents = [
        '<!-- DO NOT COMMIT! -->',
        '<!-- This file was autogenerated by core/build.js to allow for experimental preview of @labkey/api. -->',
        '<libraries xmlns="http://labkey.org/clientLibrary/xml/">',
        '    <library compileInProductionMode="false">',
        '       <script path="clientapi/labkey-api-js-core.min.js"/>',
        '    </library>',
        '</libraries>'
    ].join('\n');

    fs.writeFile(clientLibDir + clientLibFileName, libContents);
    log('Done.\n');
}

if (USE_LABKEY_API === true) {
    installDependencies();
    copyAPIFiles();
    overwriteLibXML();
}