/*
 * Copyright (c) 2016-2026 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.labkey.gradle.task.ServerSideJS
import org.labkey.gradle.util.GroupNames
import org.labkey.gradle.util.BuildUtils
import org.labkey.gradle.util.ExternalDependency

plugins {
    id 'org.labkey.build.module'
}

project.tasks.register("serverSideJS", ServerSideJS) {
    ServerSideJS task ->
        task.group = GroupNames.CODE_GENERATION
        task.description = "Concatenate javascript files for use on the server side"
}
project.tasks.named('processModuleResources').configure { dependsOn(project.tasks.serverSideJS) }

dependencies {
    implementation "org.eclipse.angus:angus-mail:${angusMailVersion}"
    jspImplementation "org.eclipse.angus:angus-mail:${angusMailVersion}"

    BuildUtils.addExternalDependency(
        project,
        new ExternalDependency(
            "org.apache.commons:commons-math3:${commonsMath3Version}",
            "Commons Math",
            "Apache",
            "http://commons.apache.org/math/",
            ExternalDependency.APACHE_2_LICENSE_NAME,
            ExternalDependency.APACHE_2_LICENSE_URL,
            "Lightweight, self-contained mathematics and statistics components"
        )
    )

    BuildUtils.addExternalDependency(
        project,
        new ExternalDependency(
            "org.commonmark:commonmark:${commonmarkVersion}",
            "commonmark-java",
            "commonmark",
            "https://github.com/commonmark/commonmark-java",
            ExternalDependency.BSD_2_LICENSE_NAME,
            "https://github.com/commonmark/commonmark-java/blob/main/LICENSE.txt",
            "Markdown renderer"
        )
    )

    BuildUtils.addExternalDependency(
        project,
        new ExternalDependency(
            "org.commonmark:commonmark-ext-autolink:${commonmarkVersion}",
            "commonmark-ext-autolink",
            "commonmark",
            "https://github.com/commonmark/commonmark-java",
            ExternalDependency.BSD_2_LICENSE_NAME,
            "https://github.com/commonmark/commonmark-java/blob/main/LICENSE.txt",
            "Autolink extension for Markdown renderer"
        )
    )

    BuildUtils.addExternalDependency(
        project,
        new ExternalDependency(
            "org.commonmark:commonmark-ext-heading-anchor:${commonmarkVersion}",
            "commonmark-ext-heading-anchor",
            "commonmark",
            "https://github.com/commonmark/commonmark-java",
            ExternalDependency.BSD_2_LICENSE_NAME,
            "https://github.com/commonmark/commonmark-java/blob/main/LICENSE.txt",
            "Heading anchor extension for Markdown renderer"
        )
    )

    BuildUtils.addExternalDependency(
        project,
        new ExternalDependency(
            "org.commonmark:commonmark-ext-image-attributes:${commonmarkVersion}",
            "commonmark-ext-image-attributes",
            "commonmark",
            "https://github.com/commonmark/commonmark-java",
            ExternalDependency.BSD_2_LICENSE_NAME,
            "https://github.com/commonmark/commonmark-java/blob/main/LICENSE.txt",
            "Image attributes extension for Markdown renderer"
        )
    )

    BuildUtils.addExternalDependency(
        project,
        new ExternalDependency(
            "org.commonmark:commonmark-ext-gfm-strikethrough:${commonmarkVersion}",
            "commonmark-ext-gfm-strikethrough",
            "commonmark",
            "https://github.com/commonmark/commonmark-java",
            ExternalDependency.BSD_2_LICENSE_NAME,
            "https://github.com/commonmark/commonmark-java/blob/main/LICENSE.txt",
            "Strikethrough extension for Markdown renderer"
        )
    )

    BuildUtils.addExternalDependency(
        project,
        new ExternalDependency(
            "org.commonmark:commonmark-ext-gfm-tables:${commonmarkVersion}",
            "commonmark-ext-gfm-tables",
            "commonmark",
            "https://github.com/commonmark/commonmark-java",
            ExternalDependency.BSD_2_LICENSE_NAME,
            "https://github.com/commonmark/commonmark-java/blob/main/LICENSE.txt",
            "Tables extension for Markdown renderer"
        )
    )
}

BuildUtils.addLabKeyDependency(project: project, config: "implementation", depProjectPath: BuildUtils.getBootstrapProjectPath(gradle))

sourceSets {
    main {
        resources {
            srcDirs = ['src'] // Pull in some Radeox config files
            exclude '**/*.java'
            exclude '**/*.jsp'
        }
    }
}
