/*
 * Copyright (c) 2006-2012 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.labkey.api.exp.api;

import org.jetbrains.annotations.Nullable;
import org.labkey.api.exp.ExperimentDataHandler;
import org.labkey.api.exp.ExperimentException;
import org.labkey.api.exp.XarSource;
import org.labkey.api.pipeline.PipelineJob;

import java.io.File;
import java.net.URI;
import java.sql.SQLException;

public interface ExpData extends ExpProtocolOutput
{
    public static final String DEFAULT_CPAS_TYPE = "Data";

    DataType getDataType();
    URI getDataFileURI();

    void setDataFileURI(URI uri);

    ExperimentDataHandler findDataHandler();

    String getDataFileUrl();

    @Nullable
    File getFile();

    boolean isInlineImage();

    boolean isFileOnDisk();

    /**
     * @return true if this ExpData File was generated by a PipelineJob process.
     */
    boolean isGenerated();

    void importDataFile(PipelineJob job, XarSource xarSource) throws ExperimentException, SQLException;
}
