UPDATE study.Cohort
    SET LSID='UPGRADE_REQUIRED'
    WHERE LSID IS NULL
GO

ALTER TABLE
    study.Cohort
    ALTER COLUMN LSID NVARCHAR(200) NOT NULL
GO

ALTER TABLE study.Visit
    ADD LSID NVARCHAR(200)
GO

UPDATE study.Visit
    SET LSID='UPGRADE_REQUIRED'
    WHERE LSID IS NULL
GO

ALTER TABLE
    study.Visit
    ALTER COLUMN LSID NVARCHAR(200) NOT NULL
GO

ALTER TABLE study.Study
    ADD LSID NVARCHAR(200)
GO

UPDATE study.Study
    SET LSID='UPGRADE_REQUIRED'
    WHERE LSID IS NULL
GO

ALTER TABLE
    study.Study
    ALTER COLUMN LSID NVARCHAR(200) NOT NULL
GO