import org.labkey.gradle.util.BuildUtils

plugins {
    id 'org.labkey.build.module'
}

dependencies {
    implementation "org.eclipse.angus:angus-mail:${angusMailVersion}"
    BuildUtils.addLabKeyDependency(project: project, config: "modules", depProjectPath: BuildUtils.getPlatformModuleProjectPath(project.gradle, "experiment"), depProjectConfig: "published", depExtension: "module")
    BuildUtils.addLabKeyDependency(project: project, config: "modules", depProjectPath: BuildUtils.getPlatformModuleProjectPath(project.gradle, "search"), depProjectConfig: "published", depExtension: "module")
}
