ModuleClass: org.labkey.studydesign.StudyDesignModule
Maintainer: Karl Lum <klum@labkey.com>
Organization: LabKey
OrganizationURL: https://www.labkey.com/
License: Apache 2.0
LicenseURL: http://www.apache.org/licenses/LICENSE-2.0
SupportedDatabases: mssql, pgsql
ManageVersion: true
