/*
 * Copyright (c) 2022-2026 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.labkey.api.attachments;

import org.apache.batik.anim.dom.SVGDOMImplementation;
import org.apache.batik.transcoder.TranscoderException;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.Strings;
import org.labkey.api.util.PageFlowUtil;
import org.labkey.api.util.SvgUtil;
import org.labkey.api.util.SvgUtil.Size;
import org.labkey.api.view.NotFoundException;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;

/**
 * Wraps SVG source String or Reader and applies all our standard filtering. All SVG conversion methods should require
 * SvgSource parameters to ensure filtering is applied consistently. See Issue 46634.
 */
public class SvgSource
{
    private final String _filteredSvg;
    private final Float _height;

    public SvgSource(String svg)
    {
        if (StringUtils.isBlank(svg))
            throw new NotFoundException("SVG source was empty");

        //svg MUST have right namespace for Batik, but svg generated by browser doesn't necessarily declare it
        //Since changing namespace recursively for all nodes not supported by DOM impl, just poke it in here.
        if (!svg.contains("xmlns=\"" + SVGDOMImplementation.SVG_NAMESPACE_URI + "\"") && !svg.contains("xmlns='" + SVGDOMImplementation.SVG_NAMESPACE_URI + "'"))
            svg = svg.replace("<svg", "<svg xmlns='" + SVGDOMImplementation.SVG_NAMESPACE_URI + "'");

        Size size = SvgUtil.readHeight(svg);
        _height = size != null ? size.value() : null;

        // remove xlink:title to prevent org.apache.batik.transcoder.TranscoderException (issue #16173)
        svg = svg.replace("xlink:title", "title");

        // Reject hrefs. See #45819.
        if (Strings.CI.contains(svg, "xlink:href"))
            throw new RuntimeException(new TranscoderException("The security settings do not allow any external resources to be referenced from the document"));

        _filteredSvg = svg;
    }

    public static SvgSource of(String svg)
    {
        return new SvgSource(svg);
    }

    public static SvgSource of(Reader reader) throws IOException
    {
        try (BufferedReader bufferedReader = new BufferedReader(reader))
        {
            return of(PageFlowUtil.getReaderContentsAsString(bufferedReader));
        }
    }

    public Reader getReader()
    {
        return new StringReader(_filteredSvg);
    }

    public Float getHeight()
    {
        return _height;
    }
}
