/*
 * Copyright (c) 2020-2026 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.labkey.assay.plate;

import org.labkey.api.assay.plate.WellGroup;
import org.labkey.api.data.statistics.FitFailedException;

import java.util.List;

/**
 * Provide a noop dilution curve implementation because dilution based assays like NAb won't calculate
 * cutoff or AUC information for this fit type, and will automatically ignore values generated by the empty impl.
 */
public class LinearCurveImpl extends EmptyCurveImpl
{
    public LinearCurveImpl(List<WellGroup> wellGroups, boolean assumeDecreasing, PercentCalculator percentCalculator) throws FitFailedException
    {
        super(wellGroups, assumeDecreasing, percentCalculator);
    }
}
