package org.labkey.assay.plate;

import org.labkey.api.assay.plate.WellGroup;
import org.labkey.api.data.statistics.FitFailedException;

import java.util.List;

/**
 * Provide a noop dilution curve implementation because dilution based assays like NAb won't calculate
 * cutoff or AUC information for this fit type, and will automatically ignore values generated by the empty impl.
 */
public class LinearCurveImpl extends EmptyCurveImpl
{
    public LinearCurveImpl(List<WellGroup> wellGroups, boolean assumeDecreasing, PercentCalculator percentCalculator) throws FitFailedException
    {
        super(wellGroups, assumeDecreasing, percentCalculator);
    }
}
