---
# Workflow to validate Pull Request branches
name: PR Validation

# Trigger on PR creation
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  validate_pr:
    if: github.event.pull_request.head.repo.owner.login == 'LabKey'
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR Branches
        uses: labkey-tchad/gitHubActions/validate-pr@master
        with:
          pr_base: ${{ github.event.pull_request.base.ref }}
          pr_head: ${{ github.event.pull_request.head.ref }}
          pr_number: ${{ github.event.pull_request.number }}
          pr_title: ${{ github.event.pull_request.title }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
